#!/bin/sh
# v1.00

# 補完リスト
# COMPREPLY
#
# 今カーソルがあるワードは何語目か
# COMP_CWORD
#
# コマンドラインのワードのリスト
# COM_WORDS
#

# compgen [options] -- [word]
# exsample:
#   compgen -W "one tow" --
#   compgen -c -- man
# -W  Word list.
# -c  Listup of command, executefile, directory.
# -f  Listup of files.
# -d  Listup of directory.


_test () {
  # COMPREPLY=(one two three);

  local cur prev cword
  _get_comp_words_by_ref -n : cur prev cword
  echo cur: ${cur}
  echo prev: ${prev}
  echo cword: ${cword}

}

# pathコマンドを_test()でTab補完
# complete -F _test path
_path_complete () {
  echo hoge0

#  _get_comp_words_by_ref -n : cur prev

  echo hoge1

#  local opts=$(ls ~/xvar/path/line/)

  echo hoge3

#  COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") );

}

echo hoge2
#complete -F _path_complete path

